// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice1.Data;

namespace Practice1.Migrations
{
    [DbContext(typeof(Practice1Context))]
    [Migration("20201019213327_AddTrophy")]
    partial class AddTrophy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practice1.Models.Franchise", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Coach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mascot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opponent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Stadium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Franchise");
                });

            modelBuilder.Entity("Practice1.Models.Trophy", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FranchiseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrophyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrophyPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FranchiseID");

                    b.ToTable("Trophy");
                });

            modelBuilder.Entity("Practice1.Models.Trophy", b =>
                {
                    b.HasOne("Practice1.Models.Franchise", null)
                        .WithMany("TrophyList")
                        .HasForeignKey("FranchiseID");
                });
#pragma warning restore 612, 618
        }
    }
}
